[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
jihoo-syntax = { path = "crates/jihoo-syntax" }
jihoo-ir = { path = "crates/jihoo-ir" }
jihoo-lower = { path = "crates/jihoo-lower" }
jihoo-vm = { path = "crates/jihoo-vm" }
